---

- include: common.yml
  vars:
    hosts_filter: ":!localhost:!127.0.0.1"

- hosts: cassandra
  become: yes
  roles:
    - { role: cassandra,
      tags: [ cassandra ]
    }

- hosts: datastax-opscenter
  become: yes
  roles:
    - { role: datastax-opscenter, tags: [ datastax-opscenter ] }

- hosts: datastax-agent
  become: yes
  roles:
    - { role: datastax-agent, tags: [ datastax-agent ] }

- hosts: cassandra
  roles:
    - stack-smoke-tests/cassandra
  tags: [ smoketest, cassandra ]
